version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:4.27.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - grid

  # docker exec -it chrome1 /bin/bash
  chrome1:
    image: selenium/node-chrome:4.27.0
    shm_size: 2g
    ports:
      - "7900:7900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

  chrome2:
    image: selenium/node-chrome:4.27.0
    shm_size: 2g
    ports:
      - "7901:7900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

  chrome3:
    image: selenium/node-chrome:4.27.0
    shm_size: 2g
    ports:
      - "7902:7900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

  tests:
    build:
      context: .
    image: selenium_saucedemo
    container_name: selenium_saucedemo_container
    depends_on:
      - selenium-hub
      - chrome1
      - chrome2
      - chrome3
    networks:
      - grid

networks:
  grid:
    driver: bridge
